import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

const cars = [
  { make:"Maruti Suzuki",model:"Alto K10",variant:"VXi",year:2024,exShowroomPrice:4.5,bodyType:"Hatchback",fuelType:"Petrol",transmission:"Manual",engineCC:998,mileage:24.39,safetyRating:2,seatingCapacity:5,bootSpace:214,groundClearance:160,power:"67 bhp",torque:"89 Nm",pros:'["Excellent mileage","Affordable price","Easy to drive in city"]',cons:'["Low safety rating","Basic interiors","No diesel option"]' },
  { make:"Maruti Suzuki",model:"Swift",variant:"ZXi+",year:2024,exShowroomPrice:7.3,bodyType:"Hatchback",fuelType:"Petrol",transmission:"Manual",engineCC:1197,mileage:22.56,safetyRating:3,seatingCapacity:5,bootSpace:268,groundClearance:163,power:"90 bhp",torque:"113 Nm",pros:'["Fun to drive","Good mileage","Stylish design"]',cons:'["Average safety","Small boot","Road noise at speed"]' },
  { make:"Maruti Suzuki",model:"Baleno",variant:"Alpha",year:2024,exShowroomPrice:8.0,bodyType:"Hatchback",fuelType:"Petrol",transmission:"Manual",engineCC:1197,mileage:22.35,safetyRating:3,seatingCapacity:5,bootSpace:318,groundClearance:170,power:"90 bhp",torque:"113 Nm",pros:'["Spacious cabin","Good features","Reliable engine"]',cons:'["Average safety","Dull driving dynamics","No sunroof"]' },
  { make:"Hyundai",model:"i20",variant:"Asta(O)",year:2024,exShowroomPrice:9.5,bodyType:"Hatchback",fuelType:"Petrol",transmission:"Automatic",engineCC:1197,mileage:20.35,safetyRating:3,seatingCapacity:5,bootSpace:311,groundClearance:170,power:"88 bhp",torque:"115 Nm",pros:'["Feature rich","Premium interiors","Sunroof available"]',cons:'["Pricey for segment","Average mileage","Turbo only in top trim"]' },
  { make:"Tata",model:"Altroz",variant:"XZ+",year:2024,exShowroomPrice:8.2,bodyType:"Hatchback",fuelType:"Petrol",transmission:"Manual",engineCC:1199,mileage:22.07,safetyRating:5,seatingCapacity:5,bootSpace:345,groundClearance:165,power:"86 bhp",torque:"113 Nm",pros:'["5-star safety","Large boot space","Solid build quality"]',cons:'["No automatic in petrol","Slow acceleration","Average infotainment"]' },
  { make:"Maruti Suzuki",model:"Dzire",variant:"ZXi+",year:2024,exShowroomPrice:8.8,bodyType:"Sedan",fuelType:"Petrol",transmission:"Automatic",engineCC:1197,mileage:22.61,safetyRating:3,seatingCapacity:5,bootSpace:378,groundClearance:163,power:"90 bhp",torque:"113 Nm",pros:'["Best-in-class mileage","Spacious rear seat","Smooth automatic"]',cons:'["Plain design","Average safety","Limited features"]' },
  { make:"Honda",model:"Amaze",variant:"VX CVT",year:2024,exShowroomPrice:9.2,bodyType:"Sedan",fuelType:"Petrol",transmission:"Automatic",engineCC:1199,mileage:18.6,safetyRating:4,seatingCapacity:5,bootSpace:420,groundClearance:170,power:"90 bhp",torque:"110 Nm",pros:'["Honda reliability","Largest boot in segment","Good safety"]',cons:'["Dated design","CVT feels sluggish","No sunroof"]' },
  { make:"Hyundai",model:"Aura",variant:"SX+ CNG",year:2024,exShowroomPrice:8.9,bodyType:"Sedan",fuelType:"Petrol",transmission:"Manual",engineCC:1197,mileage:20.5,safetyRating:3,seatingCapacity:5,bootSpace:402,groundClearance:170,power:"83 bhp",torque:"114 Nm",pros:'["CNG option available","Good features list","Connected car tech"]',cons:'["Average build quality","Boot space reduced with CNG","Basic safety"]' },
  { make:"Honda",model:"City",variant:"ZX CVT",year:2024,exShowroomPrice:14.5,bodyType:"Sedan",fuelType:"Petrol",transmission:"Automatic",engineCC:1498,mileage:17.8,safetyRating:4,seatingCapacity:5,bootSpace:506,groundClearance:165,power:"121 bhp",torque:"145 Nm",pros:'["Powerful engine","ADAS features","Largest boot"]',cons:'["Expensive for sedan","Road noise","Firm ride quality"]' },
  { make:"Hyundai",model:"Verna",variant:"SX(O) Turbo DCT",year:2024,exShowroomPrice:15.5,bodyType:"Sedan",fuelType:"Petrol",transmission:"Automatic",engineCC:1482,mileage:20.6,safetyRating:5,seatingCapacity:5,bootSpace:480,groundClearance:170,power:"160 bhp",torque:"253 Nm",pros:'["5-star safety","Powerful turbo engine","Feature loaded"]',cons:'["Expensive top variant","Firm ride","Turbo lag at low RPM"]' },
  { make:"Skoda",model:"Slavia",variant:"Style 1.5 TSI DSG",year:2024,exShowroomPrice:16.0,bodyType:"Sedan",fuelType:"Petrol",transmission:"Automatic",engineCC:1498,mileage:18.7,safetyRating:4,seatingCapacity:5,bootSpace:521,groundClearance:179,power:"150 bhp",torque:"250 Nm",pros:'["Best handling in segment","Huge boot","Premium feel"]',cons:'["Expensive maintenance","No diesel","Average rear seat"]' },
  { make:"Tata",model:"Nexon",variant:"XZ+(S) Diesel",year:2024,exShowroomPrice:12.0,bodyType:"SUV",fuelType:"Diesel",transmission:"Manual",engineCC:1497,mileage:23.22,safetyRating:5,seatingCapacity:5,bootSpace:350,groundClearance:209,power:"115 bhp",torque:"260 Nm",pros:'["5-star safety","High ground clearance","Diesel efficiency"]',cons:'["Cramped rear seat","Turbo lag","Boot space average"]' },
  { make:"Hyundai",model:"Venue",variant:"SX(O) Turbo DCT",year:2024,exShowroomPrice:12.5,bodyType:"SUV",fuelType:"Petrol",transmission:"Automatic",engineCC:998,mileage:18.27,safetyRating:4,seatingCapacity:5,bootSpace:350,groundClearance:195,power:"120 bhp",torque:"172 Nm",pros:'["Connected car features","Punchy turbo engine","Compact city SUV"]',cons:'["Small for families","No rear AC vents","Average ride quality"]' },
  { make:"Kia",model:"Sonet",variant:"HTX+ Turbo iMT",year:2024,exShowroomPrice:12.0,bodyType:"SUV",fuelType:"Petrol",transmission:"Manual",engineCC:998,mileage:18.2,safetyRating:3,seatingCapacity:5,bootSpace:392,groundClearance:211,power:"120 bhp",torque:"172 Nm",pros:'["Feature rich","Air purifier","Ventilated seats"]',cons:'["Average safety rating","Cramped 3rd row","Stiff ride"]' },
  { make:"Maruti Suzuki",model:"Brezza",variant:"ZXi+ AT",year:2024,exShowroomPrice:12.8,bodyType:"SUV",fuelType:"Petrol",transmission:"Automatic",engineCC:1462,mileage:19.8,safetyRating:4,seatingCapacity:5,bootSpace:328,groundClearance:198,power:"103 bhp",torque:"137 Nm",pros:'["Smooth 6-speed auto","CNG option","Maruti service network"]',cons:'["Underpowered","Average interiors","No diesel option"]' },
  { make:"Hyundai",model:"Creta",variant:"SX(O) 1.5T DCT",year:2024,exShowroomPrice:18.5,bodyType:"SUV",fuelType:"Petrol",transmission:"Automatic",engineCC:1482,mileage:17.0,safetyRating:5,seatingCapacity:5,bootSpace:433,groundClearance:190,power:"160 bhp",torque:"253 Nm",pros:'["5-star safety","Panoramic sunroof","ADAS Level 2"]',cons:'["Expensive top trim","Average ground clearance","Firm suspension"]' },
  { make:"Kia",model:"Seltos",variant:"HTX+ 1.5T DCT",year:2024,exShowroomPrice:17.5,bodyType:"SUV",fuelType:"Petrol",transmission:"Automatic",engineCC:1482,mileage:17.7,safetyRating:5,seatingCapacity:5,bootSpace:433,groundClearance:190,power:"160 bhp",torque:"253 Nm",pros:'["5-star safety","Feature loaded","Sporty design"]',cons:'["Firm ride quality","Turbo lag at low RPM","No 4WD"]' },
  { make:"Tata",model:"Harrier",variant:"XZA+ Dark",year:2024,exShowroomPrice:20.5,bodyType:"SUV",fuelType:"Diesel",transmission:"Automatic",engineCC:1956,mileage:16.35,safetyRating:5,seatingCapacity:5,bootSpace:425,groundClearance:198,power:"170 bhp",torque:"350 Nm",pros:'["5-star safety","Commanding road presence","Powerful diesel"]',cons:'["No petrol option","Average infotainment","Heavy steering"]' },
  { make:"MG",model:"Hector",variant:"Sharp Pro CVT",year:2024,exShowroomPrice:19.5,bodyType:"SUV",fuelType:"Petrol",transmission:"Automatic",engineCC:1451,mileage:14.8,safetyRating:4,seatingCapacity:5,bootSpace:587,groundClearance:192,power:"143 bhp",torque:"250 Nm",pros:'["Massive boot space","14-inch infotainment","Panoramic sunroof"]',cons:'["Average mileage","CVT feels lazy","Heavy to maneuver"]' },
  { make:"Mahindra",model:"XUV700",variant:"AX7 L Diesel AT",year:2024,exShowroomPrice:23.5,bodyType:"SUV",fuelType:"Diesel",transmission:"Automatic",engineCC:2184,mileage:16.0,safetyRating:5,seatingCapacity:7,bootSpace:451,groundClearance:200,power:"185 bhp",torque:"420 Nm",pros:'["5-star safety","7-seater option","ADAS features"]',cons:'["Long waiting period","Quality inconsistencies","Noisy diesel"]' },
  { make:"Mahindra",model:"Thar",variant:"LX Hard Top Diesel AT",year:2024,exShowroomPrice:16.5,bodyType:"SUV",fuelType:"Diesel",transmission:"Automatic",engineCC:2184,mileage:15.2,safetyRating:4,seatingCapacity:4,bootSpace:300,groundClearance:226,power:"130 bhp",torque:"300 Nm",pros:'["True 4x4 capability","Iconic design","High ground clearance"]',cons:'["Rough ride on road","Limited boot space","Noisy cabin"]' },
  { make:"Tata",model:"Nexon EV",variant:"Max XZ+ LR",year:2024,exShowroomPrice:18.0,bodyType:"SUV",fuelType:"Electric",transmission:"Automatic",engineCC:0,mileage:40.5,safetyRating:5,seatingCapacity:5,bootSpace:350,groundClearance:209,power:"143 bhp",torque:"215 Nm",pros:'["5-star safety","Best EV range in segment","Low running cost"]',cons:'["Charging infrastructure","Heavy battery weight","Premium pricing"]' },
  { make:"MG",model:"ZS EV",variant:"Excite Pro",year:2024,exShowroomPrice:22.0,bodyType:"SUV",fuelType:"Electric",transmission:"Automatic",engineCC:0,mileage:38.0,safetyRating:4,seatingCapacity:5,bootSpace:448,groundClearance:177,power:"176 bhp",torque:"280 Nm",pros:'["Good range","Fast charging support","Feature loaded"]',cons:'["Expensive","Low ground clearance","Average build quality"]' },
  { make:"Maruti Suzuki",model:"Ertiga",variant:"ZXi+ AT",year:2024,exShowroomPrice:12.5,bodyType:"MPV",fuelType:"Petrol",transmission:"Automatic",engineCC:1462,mileage:19.01,safetyRating:3,seatingCapacity:7,bootSpace:209,groundClearance:185,power:"103 bhp",torque:"137 Nm",pros:'["Best value 7-seater","Good mileage","Maruti reliability"]',cons:'["Underpowered","Third row cramped","Basic safety"]' },
  { make:"Kia",model:"Carens",variant:"Luxury Plus 1.5T DCT",year:2024,exShowroomPrice:16.5,bodyType:"MPV",fuelType:"Petrol",transmission:"Automatic",engineCC:1482,mileage:16.5,safetyRating:3,seatingCapacity:7,bootSpace:216,groundClearance:195,power:"160 bhp",torque:"253 Nm",pros:'["Powerful turbo engine","Feature loaded","Ventilated seats"]',cons:'["Average safety rating","Third row tight","No diesel auto"]' },
  { make:"Toyota",model:"Innova Hycross",variant:"ZX(O) Hybrid",year:2024,exShowroomPrice:24.0,bodyType:"MPV",fuelType:"Hybrid",transmission:"Automatic",engineCC:1987,mileage:21.1,safetyRating:5,seatingCapacity:7,bootSpace:300,groundClearance:185,power:"186 bhp",torque:"188 Nm",pros:'["Hybrid efficiency","Toyota reliability","Spacious cabin"]',cons:'["Very expensive","Long waiting period","Captain seats only in top trim"]' },
  { make:"Mahindra",model:"Scorpio N",variant:"Z8 L Diesel AT 4WD",year:2024,exShowroomPrice:21.0,bodyType:"SUV",fuelType:"Diesel",transmission:"Automatic",engineCC:2184,mileage:15.31,safetyRating:5,seatingCapacity:7,bootSpace:460,groundClearance:203,power:"175 bhp",torque:"370 Nm",pros:'["5-star safety","True 4WD","Powerful diesel"]',cons:'["Rough ride","Heavy steering","Third row cramped"]' },
  { make:"Tata",model:"Punch",variant:"Adventure Rhythm",year:2024,exShowroomPrice:7.0,bodyType:"SUV",fuelType:"Petrol",transmission:"Manual",engineCC:1199,mileage:20.09,safetyRating:5,seatingCapacity:5,bootSpace:366,groundClearance:187,power:"86 bhp",torque:"113 Nm",pros:'["5-star safety","High ground clearance for price","Fun design"]',cons:'["Underpowered","No automatic in base","Road noise"]' },
  { make:"Hyundai",model:"Exter",variant:"SX+ Connect AMT",year:2024,exShowroomPrice:8.5,bodyType:"SUV",fuelType:"Petrol",transmission:"Automatic",engineCC:1197,mileage:19.4,safetyRating:3,seatingCapacity:5,bootSpace:391,groundClearance:185,power:"83 bhp",torque:"114 Nm",pros:'["Dash cam integrated","Good boot space","Connected features"]',cons:'["AMT not smooth","Underpowered","Average safety"]' },
  { make:"Volkswagen",model:"Taigun",variant:"GT Plus 1.5 TSI DSG",year:2024,exShowroomPrice:17.0,bodyType:"SUV",fuelType:"Petrol",transmission:"Automatic",engineCC:1498,mileage:18.23,safetyRating:5,seatingCapacity:5,bootSpace:385,groundClearance:188,power:"150 bhp",torque:"250 Nm",pros:'["5-star safety","Best handling SUV","Premium interiors"]',cons:'["Expensive maintenance","No diesel","Average rear space"]' },
];

async function main() {
  console.log("Seeding database with", cars.length, "cars...");
  await prisma.car.deleteMany();
  for (const car of cars) {
    await prisma.car.create({ data: car });
  }
  console.log("✅ Seeded", cars.length, "cars successfully!");
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
